-- SQL para criar a tabela compartilhada usada pelo portal de notícias
-- Execute no SQL Editor do Supabase do projeto real.

create table if not exists public.pz_news_articles (
  id text primary key,
  payload jsonb not null default '{}'::jsonb,
  deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_pz_news_articles_updated_at
  on public.pz_news_articles (updated_at desc);

create index if not exists idx_pz_news_articles_deleted
  on public.pz_news_articles (deleted);

create table if not exists public.pz_news_users (
  id text primary key,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_pz_news_users_updated_at on public.pz_news_users (updated_at desc);

create table if not exists public.pz_news_settings (
  id text primary key,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
alter table public.pz_news_settings enable row level security;
create index if not exists idx_pz_news_settings_updated_at on public.pz_news_settings (updated_at desc);
drop policy if exists "service_role_settings_access" on public.pz_news_settings;
create policy "service_role_settings_access" on public.pz_news_settings for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

create table if not exists public.pz_news_comments (
  id text primary key,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_pz_news_comments_updated_at on public.pz_news_comments (updated_at desc);
alter table public.pz_news_comments enable row level security;

create table if not exists public.pz_news_analytics_events (
  id text primary key,
  event_type text not null check (event_type in ('article_view', 'article_share', 'page_view')),
  article_id text,
  category text,
  author_user_ids jsonb not null default '[]'::jsonb,
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists idx_pz_news_analytics_events_occurred_at
  on public.pz_news_analytics_events (occurred_at desc);
create index if not exists idx_pz_news_analytics_events_article
  on public.pz_news_analytics_events (article_id, occurred_at desc);
alter table public.pz_news_analytics_events enable row level security;
alter table public.pz_news_users enable row level security;
create policy "admin_users_service_role_access" on public.pz_news_users for all using (true) with check (true);

alter table public.pz_news_articles enable row level security;

-- Leitura pública: só artigos não deletados
create policy "public_read_non_deleted_articles"
  on public.pz_news_articles
  for select
  using (deleted = false);

-- Escrita do admin: permissivo para funcionar com a app atual sem auth do Supabase
create policy "admin_insert_articles"
  on public.pz_news_articles
  for insert
  with check (true);

create policy "admin_update_articles"
  on public.pz_news_articles
  for update
  using (true)
  with check (true);

create policy "admin_delete_articles"
  on public.pz_news_articles
  for delete
  using (true);

-- Opcional: manter updated_at em qualquer escrita
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_set_updated_at on public.pz_news_articles;
create trigger trg_set_updated_at
before update on public.pz_news_articles
for each row
execute function public.set_updated_at();

-- Armazena tokens OAuth por usuário/provedor sem expor no payload público de usuários
create table if not exists public.pz_news_user_integrations (
  id bigint generated by default as identity primary key,
  user_id text not null,
  provider text not null check (provider in ('linkedin', 'teams')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider)
);

create index if not exists idx_pz_news_user_integrations_user
  on public.pz_news_user_integrations (user_id);

create index if not exists idx_pz_news_user_integrations_provider
  on public.pz_news_user_integrations (provider);

drop trigger if exists trg_set_updated_at_integrations on public.pz_news_user_integrations;
create trigger trg_set_updated_at_integrations
before update on public.pz_news_user_integrations
for each row
execute function public.set_updated_at();

-- Comunicação interna: a API sempre filtra pelo participante autenticado.
create table if not exists public.rbn_message_conversations (
  id text primary key,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_rbn_message_conversations_updated_at on public.rbn_message_conversations (updated_at desc);

create table if not exists public.rbn_messages (
  id text primary key,
  conversation_id text not null references public.rbn_message_conversations(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_rbn_messages_conversation_created on public.rbn_messages (conversation_id, created_at);

create table if not exists public.rbn_message_notifications (
  id text primary key,
  user_id text not null,
  conversation_id text not null references public.rbn_message_conversations(id) on delete cascade,
  message_id text not null references public.rbn_messages(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  read_at timestamptz
);
create index if not exists idx_rbn_message_notifications_user_unread
  on public.rbn_message_notifications (user_id, read_at, created_at desc);

alter table public.rbn_message_conversations enable row level security;
alter table public.rbn_messages enable row level security;
alter table public.rbn_message_notifications enable row level security;
create policy "service_role_messages_access" on public.rbn_message_conversations for all using (true) with check (true);
create policy "service_role_message_rows_access" on public.rbn_messages for all using (true) with check (true);
create policy "service_role_message_notifications_access" on public.rbn_message_notifications for all using (true) with check (true);

-- Documentação privada da equipe. Os arquivos ficam em coluna protegida e só
-- são entregues pela API após autorização do administrador.
create table if not exists public.pz_news_team_documents (
  id text primary key,
  user_id text not null,
  document_type text not null,
  file_name text,
  mime_type text,
  size_bytes bigint,
  status text not null default 'pending' check (status in ('pending', 'review', 'approved', 'rejected', 'expired')),
  expires_at date,
  notes text,
  request_reason text,
  content_base64 text,
  requested_by text,
  uploaded_by text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_pz_news_team_documents_user on public.pz_news_team_documents (user_id, updated_at desc);
create index if not exists idx_pz_news_team_documents_status on public.pz_news_team_documents (status, updated_at desc);
alter table public.pz_news_team_documents add column if not exists deleted_at timestamptz;
alter table public.pz_news_team_documents enable row level security;
drop policy if exists "service_role_team_documents_access" on public.pz_news_team_documents;
create policy "service_role_team_documents_access" on public.pz_news_team_documents for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
drop trigger if exists trg_set_updated_at_team_documents on public.pz_news_team_documents;
create trigger trg_set_updated_at_team_documents
before update on public.pz_news_team_documents
for each row execute function public.set_updated_at();

create table if not exists public.pz_news_team_document_audit (
  id text primary key,
  document_id text not null references public.pz_news_team_documents(id) on delete cascade,
  user_id text not null,
  actor_id text not null,
  action text not null,
  from_status text,
  to_status text,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_pz_news_team_document_audit_document on public.pz_news_team_document_audit (document_id, created_at desc);
alter table public.pz_news_team_document_audit enable row level security;
drop policy if exists "service_role_team_document_audit_access" on public.pz_news_team_document_audit;
create policy "service_role_team_document_audit_access" on public.pz_news_team_document_audit for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
