-- PostgreSQL schema equivalent to the Supabase tables currently used by the portal.
-- This file does not mutate live Supabase data. It is intended for a new PostgreSQL instance.

CREATE TABLE IF NOT EXISTS public.pz_news_articles (
  id text PRIMARY KEY,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pz_news_articles_updated_at
  ON public.pz_news_articles (updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_pz_news_articles_deleted
  ON public.pz_news_articles (deleted);

CREATE TABLE IF NOT EXISTS public.pz_news_comments (
  id text PRIMARY KEY,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pz_news_comments_updated_at
  ON public.pz_news_comments (updated_at DESC);

CREATE TABLE IF NOT EXISTS public.pz_news_analytics_events (
  id text PRIMARY KEY,
  event_type text NOT NULL CHECK (event_type IN ('article_view', 'article_share', 'page_view')),
  article_id text,
  category text,
  author_user_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_pz_news_analytics_events_occurred_at
  ON public.pz_news_analytics_events (occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_pz_news_analytics_events_article
  ON public.pz_news_analytics_events (article_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS public.pz_news_users (
  id text PRIMARY KEY,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pz_news_users_updated_at
  ON public.pz_news_users (updated_at DESC);

CREATE TABLE IF NOT EXISTS public.pz_news_user_integrations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  provider text NOT NULL CHECK (provider IN ('linkedin', 'teams')),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, provider)
);

CREATE INDEX IF NOT EXISTS idx_pz_news_user_integrations_user
  ON public.pz_news_user_integrations (user_id);

CREATE INDEX IF NOT EXISTS idx_pz_news_user_integrations_provider
  ON public.pz_news_user_integrations (provider);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_updated_at_articles ON public.pz_news_articles;
CREATE TRIGGER trg_set_updated_at_articles
BEFORE UPDATE ON public.pz_news_articles
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_set_updated_at_comments ON public.pz_news_comments;
CREATE TRIGGER trg_set_updated_at_comments
BEFORE UPDATE ON public.pz_news_comments
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_set_updated_at_users ON public.pz_news_users;
CREATE TRIGGER trg_set_updated_at_users
BEFORE UPDATE ON public.pz_news_users
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_set_updated_at_integrations ON public.pz_news_user_integrations;
CREATE TRIGGER trg_set_updated_at_integrations
BEFORE UPDATE ON public.pz_news_user_integrations
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.rbn_message_conversations (
  id text PRIMARY KEY,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_rbn_message_conversations_updated_at ON public.rbn_message_conversations (updated_at DESC);

CREATE TABLE IF NOT EXISTS public.rbn_messages (
  id text PRIMARY KEY,
  conversation_id text NOT NULL REFERENCES public.rbn_message_conversations(id) ON DELETE CASCADE,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_rbn_messages_conversation_created ON public.rbn_messages (conversation_id, created_at);

CREATE TABLE IF NOT EXISTS public.rbn_message_notifications (
  id text PRIMARY KEY,
  user_id text NOT NULL,
  conversation_id text NOT NULL REFERENCES public.rbn_message_conversations(id) ON DELETE CASCADE,
  message_id text NOT NULL REFERENCES public.rbn_messages(id) ON DELETE CASCADE,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  read_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_rbn_message_notifications_user_unread ON public.rbn_message_notifications (user_id, read_at, created_at DESC);

CREATE TABLE IF NOT EXISTS public.rbn_auth_sessions (
  id text PRIMARY KEY,
  user_id text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_rbn_auth_sessions_user
  ON public.rbn_auth_sessions (user_id);
