-- PostgreSQL schema equivalent to the Supabase tables currently used by the portal.
-- This file does not mutate live Supabase data. It is intended for a new PostgreSQL instance.

CREATE TABLE IF NOT EXISTS public.pz_news_articles (
  id text PRIMARY KEY,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  deleted boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pz_news_articles_updated_at
  ON public.pz_news_articles (updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_pz_news_articles_deleted
  ON public.pz_news_articles (deleted);

CREATE TABLE IF NOT EXISTS public.pz_news_comments (
  id text PRIMARY KEY,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pz_news_comments_updated_at
  ON public.pz_news_comments (updated_at DESC);

CREATE TABLE IF NOT EXISTS public.pz_news_users (
  id text PRIMARY KEY,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pz_news_users_updated_at
  ON public.pz_news_users (updated_at DESC);

CREATE TABLE IF NOT EXISTS public.pz_news_user_integrations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  provider text NOT NULL CHECK (provider IN ('linkedin', 'teams')),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, provider)
);

CREATE INDEX IF NOT EXISTS idx_pz_news_user_integrations_user
  ON public.pz_news_user_integrations (user_id);

CREATE INDEX IF NOT EXISTS idx_pz_news_user_integrations_provider
  ON public.pz_news_user_integrations (provider);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_updated_at_articles ON public.pz_news_articles;
CREATE TRIGGER trg_set_updated_at_articles
BEFORE UPDATE ON public.pz_news_articles
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_set_updated_at_comments ON public.pz_news_comments;
CREATE TRIGGER trg_set_updated_at_comments
BEFORE UPDATE ON public.pz_news_comments
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_set_updated_at_users ON public.pz_news_users;
CREATE TRIGGER trg_set_updated_at_users
BEFORE UPDATE ON public.pz_news_users
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_set_updated_at_integrations ON public.pz_news_user_integrations;
CREATE TRIGGER trg_set_updated_at_integrations
BEFORE UPDATE ON public.pz_news_user_integrations
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.rbn_auth_sessions (
  id text PRIMARY KEY,
  user_id text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_rbn_auth_sessions_user
  ON public.rbn_auth_sessions (user_id);
